export default function Disclaimer() {
  return (
    <>
      <div className="disclaimer-parent">
        <h2>
          An important note on{" "}
          <span className="main-nav-bar-home-allegations">Allegations</span>
          .wiki:{" "}
        </h2>
        <p>
          Please note{" "}
          <span className="main-nav-bar-home-allegations">Allegations</span>
          .wiki is not intended to be taken seriously - so please don't take it
          as such. The <br />'
          <span className="main-nav-bar-home-allegations">Cancelled</span>{" "}
          statuses'
          <br /> of individuals seen on this website are generated by a Machine
          Learning algorithm fed with biased data by a biased individual
          and <span style={{textDecoration:"underline"}}>may or may not represent reality.</span>{" "}
          <p>That is for you decide for yourself. </p>
        </p>
      </div>
    </>
  );
}
